"""update product manufactuer field

Revision ID: 361ce76c54bb
Revises: 6af83b8b94e3
Create Date: 2023-11-22 11:35:06.572878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '361ce76c54bb'
down_revision: Union[str, None] = '6af83b8b94e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'departments', 'users', ['head_id'], ['id'])
    op.add_column('products', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.drop_column('products', 'manufucturer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('manufucturer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'manufacturer_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    # ### end Alembic commands ###
