"""update relationships new

Revision ID: 62fda244a1be
Revises: 1ea3286038c3
Create Date: 2023-11-22 09:12:29.515867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62fda244a1be'
down_revision: Union[str, None] = '1ea3286038c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'departments', 'users', ['head_id'], ['id'])
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    # ### end Alembic commands ###
