"""added department field

Revision ID: 6af83b8b94e3
Revises: 62fda244a1be
Create Date: 2023-11-22 09:14:46.395360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af83b8b94e3'
down_revision: Union[str, None] = '62fda244a1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'departments', 'users', ['head_id'], ['id'])
    op.add_column('users', sa.Column('department', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    # ### end Alembic commands ###
