"""update relationships 3

Revision ID: e66452d855a4
Revises: af4f059a9969
Create Date: 2023-11-21 21:47:50.157873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e66452d855a4'
down_revision: Union[str, None] = 'af4f059a9969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('head_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['head_id'], ['id'])
    op.drop_column('departments', 'head')
    op.create_foreign_key(None, 'users', 'departments', ['department'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('departments', sa.Column('head', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'head_id')
    # ### end Alembic commands ###
